### ISSUE TITLE
FCReplay Game Support Request: Beat Em Ups from Capcom, Irem, Konami, Sega, SNK, and Technos

### ISSUE THREAD

**Issue by MasterO2** [glisignoli/fcreplay#100]
@glisignoli

Just make sure the romnames match up with their respective FC2 lobbies.  Some of the Konami games use clones for their respective FC2 lobbies.

Also, I am sure there are other arcade beat em ups that I am missing, but this should cover the most popular ones.

### Capcom Arcade Beat Em Ups and Platformers

romname: **avsp**
gamename: Alien Vs. Predator

romname: **armwar**
gamename: Armored Warriors 

romname: **batcir**
gamename: Battle Circuit

romname: **dino**
gamename: Cadillacs And Dinosaurs

romname: **captcomm**
gamename: Captain Commando

romname: **ddtod**
gamename: Dungeons & Dragons: Tower Of Doom

romname: **ffight**
gamename: Final Fight

romname: **kod**
gamename: The King Of Dragons

romname: **knights**
gamename: Knights Of The Round

romname: **msword**
gamename: Magic Sword

romname: **nemo**
gamename: Nemo

romname: **punisher**
gamename: The Punisher

romname: **3wonders**
gamename: Three Wonders

romname: **wof**
gamename: Warriors Of Fate Aka Tenchi Wo Kurau Ii

### Irem Arcade Beat Em Ups

romname: **nbbatman**
gamename: Ninja Baseball Batman

romname: **uccopsaru**
gamename: Undercover Cops

### Konami Arcade Beat Em Ups

romname: **asterix**
gamename: Asterix

romname: **bucky**
gamename: Bucky O'Hare

romname: **crimfght**
gamename: Crime Fighters

romname: **metamrphj**
gamename: Metamorphic Force

romname: **simpsons2p**
gamename: The Simpsons

romname: **tmnt2po**
gamename: Teenage Mutant Ninja Turtles

romname: **tmnt22pu**
gamename: Teenage Mutant Ninja Turtles: Turtles In Time

romname: **vendetta2pw**
gamename: Vendetta

romname: **viostorm**
gamename: Violent Storm

romname: **xmen2pe**
gamename: X-Men

### Sega Arcade Beat Em Ups

romname: **altbeast**
gamename: Altered Beast

romname: **goldnaxe**
gamename: Golden Axe

### SNK Neo-Geo Arcade Beat Em Ups

romname: **burningf**
gamename: Burning Fight

romname: **crsword**
gamename: Crossed Swords

romname: **mutnat**
gamename: Mutation Nation

romname: **roboarmy**
gamename: Robo Army

romname: **sengoku**
gamename: Sengoku 1

romname: **sengoku2**
gamename: Sengoku 2

romname: **sengoku3**
gamename: Sengoku 3

### Technos Beat Em Up Arcade Games

romname: **ddragon**
game name: Double Dragon (Japan)

romname: **ddragon2**
gamename: Double Dragon II - The Revenge

romname:  **ddragon3**
gamename:  Double Dragon 3 - The Rosetta Stone (World)

romname:  **ddragon3j**
gamename:  Double Dragon 3 - The Rosetta Stone (Japan)

Note: For some reason, Double Dragon 3 has two FC2 lobbies.

**Comment by glisignoli** [comment]
Not going to add these games quite yet, going to see how the encoding queue holds up. But here is the formatted json.

I'll have to also check to see if any game names overlap (I think Double Dragon might).

```json
{
    "avsp": {
        "game_name": "Alien vs Predator"
    },
    "armwar": {
        "game_name": "Armored Warriors"
    },
    "batcir": {
        "game_name": "Battle Circuit"
    },
    "dino": {
        "game_name": "Cadillacs & Dinosaurs"
    },
    "captcomm": {
        "game_name": "Captain Commando"
    },
    "ddtod": {
        "game_name": "Dungeons & Dragons - tower of doom"
    },
    "ffight": {
        "game_name": "Final Fight"
    },
    "kod": {
        "game_name": "The King of Dragons"
    },
    "knights": {
        "game_name": "Knights of the Round"
    },
    "msword": {
        "game_name": "Magic Sword - heroic fantasy"
    },
    "nemo": {
        "game_name": "Nemo"
    },
    "punisher": {
        "game_name": "The Punisher"
    },
    "3wonders": {
        "game_name": "Three Wonders"
    },
    "wof": {
        "game_name": "Warriors of Fate"
    },
    "nbbatman": {
        "game_name": "Ninja Baseball Batman"
    },
    "uccopsar": {
        "game_name": "Undercover Cops"
    },
    "asterix": {
        "game_name": "Asterix"
    },
    "bucky": {
        "game_name": "Bucky O'Hare"
    },
    "crimfght": {
        "game_name": "Crime Fighters"
    },
    "metamrphj": {
        "game_name": "Metamorphic Force"
    },
    "simpsons2p": {
        "game_name": "The Simpsons"
    },
    "tmnt2po": {
        "game_name": "Teenage Mutant Ninja Turtles"
    },
    "tmnt22pu": {
        "game_name": "Teenage Mutant Ninja Turtles - Turtles in Time"
    },
    "vendetta2pw": {
        "game_name": "Vendetta"
    },
    "viostorm": {
        "game_name": "Violent Storm"
    },
    "xmen2pe": {
        "game_name": "X-Men"
    },
    "altbeast": {
        "game_name": "Altered Beast"
    },
    "goldnaxe": {
        "game_name": "Golden Axe"
    },
    "burningf": {
        "game_name": "Burning Fight"
    },
    "crsword": {
        "game_name": "Crossed Swords"
    },
    "mutnat": {
        "game_name": "Mutation Nation"
    },
    "roboarmy": {
        "game_name": "Robo Army"
    },
    "sengoku": {
        "game_name": "Sengoku"
    },
    "sengoku2": {
        "game_name": "Sengoku 2"
    },
    "sengoku3": {
        "game_name": "Sengoku 3"
    },
    "ddragon": {
        "game_name": "Double Dragon"
    },
    "ddragon2": {
        "game_name": "Double Dragon II - The Revenge"
    },
    "ddragon3": {
        "game_name": "Double Dragon 3 - The Rosetta Stone (US)"
    },
    "ddragon3j": {
        "game_name": "Double Dragon 3 - The Rosetta Stone (Japan)"
    }
}```

**Comment by glisignoli** [comment]
Games are added!
