### ISSUE TITLE
FCReplay Game Support Request:  Arcade Co-Op Shmups (Space Shooters) from Multiple Companies

### ISSUE THREAD

**Issue by MasterO2** [glisignoli/fcreplay#105]
@glisignoli 

No rush, by the way.  

All of the shmups below are capable of 2-player coop:

### **Cave:**

    "agallet": {
        "game_name": "Air Gallet"
    }
	
	"ddonpach": {
        "game_name": "DoDonPachi"
    }
	
	"esprade": {
        "game_name": "ESP Ra.De"
    }
	
	"guwange": {
        "game_name": "Guwange"
    }
	
	"ket": {
        "game_name": "Ketsui Kizuna Jigoku Tachi"
    }

### **Capcom:**

    "1941": {
        "game_name": "1941 - Counter Attack"
    },
	
	
    "1943": {
        "game_name": "1943: The Battle of Midway"
    },
	
	
    "19xx": {
        "game_name": "19XX - the war against destiny"
    },
	
	
    "unsquad": {
        "game_name": "Area 88 / UN Squadron"
    },

    "cawing": {
        "game_name": "Carrier Air Wing / US Navy"
    },

    "ecofghtr": {
        "game_name": "Eco Fighters"
    },
	
	"exedexes": {
        "game_name": "Exed Exes"
    },
	
	"forgottn": {
        "game_name": "Forgotten Worlds"
    },
	
	"gigawing": {
        "game_name": "Giga Wing"
    },
	
	"lastduel": {
        "game_name": "Last Duel"
    },
	
	"lwings": {
        "game_name": "Legendary Wings"
    },
	
	"mmatrix": {
        "game_name": "Mars Matrix"
    },
	
	"progear": {
        "game_name": "Progear"
    },
	
	"sidearms": {
        "game_name": "Side Arms - Hyper Dyne"
    },
	
	"varth": {
        "game_name": "Varth - Operation Thunderstorm"
    }

### **Irem:**

     "inthunt": {
        "game_name": "In The Hunt"
    },
	
	"rtypeleo": {
        "game_name": "R-Type Leo"
    }

### **Konami:**

  ```
"salamand": {
        "game_name": "Salamander"
    }
```

### **Seibu Kaihatsu:**

    "raiden": {
        "game_name": "Raiden"
    },
	
	"raiden2": {
        "game_name": "Raiden II"
    },
	
	"raidendx": {
        "game_name": "Raiden DX"
    }
### 
**Taito:**

    "darius": {
        "game_name": "Darius"
    },
	
	"darius2": {
        "game_name": "Darius II (Triple Screen)"
    },
	
	"dariusg": {
        "game_name": "Darius Gaiden - Silver Hawk"
    },
	
	"dariusgx": {
        "game_name": "Darius Gaiden - Silver Hawk Extra Version"
    },
	
	"metalb": {
        "game_name": "Metal Black"
    },
	
	"spcinv95": {
        "game_name": "Space Invaders '95: The Attack Of Lunar Loonies"
    }

### **Toaplan:**

    "batsugun": {
        "game_name": "Batsugun"
    },
		
	"fireshrk": {
        "game_name": "Fire Shark"
    },

	"truxton2": {
        "game_name": "Truxton II / Tatsujin-Oh"
    }

**Comment by glisignoli** [comment]
Unfortunately, a lot of these are not 4:3 aspect ratio and my encoding is hardcoded to for that.

See: https://github.com/glisignoli/fcreplay/issues/106

I'll leave this open

**Comment by MasterO2** [comment]
Since these now have FC2 lobbies for them, I'm also requesting these be added as well:

"batsugunsp":  {
        "game_name": "Batsugun (Special Ver.)"
    },

"dariuse":  {
        "game_name": "Darius (Extra) (Japan)"
    },

"thndrx2j":  {
        "game_name": "Thunder Cross II (Japan)"
    },

"thunderxj":  {
        "game_name": "Thunder Cross ◦ サンダークロス (Japan)"
    }

**Comment by ehtrashy** [comment]
`"agallet": {
    "game_name": "Air Gallet"
	"aspect_ration": "3:4"
}

"ddonpach": {
    "game_name": "DoDonPachi"
	"aspect_ration": "3:4"
}

"esprade": {
    "game_name": "ESP Ra.De"
	"aspect_ration": "3:4"
}

"guwange": {
    "game_name": "Guwange"
	"aspect_ration": "3:4"
}

"ket": {
    "game_name": "Ketsui Kizuna Jigoku Tachi"
	"aspect_ration": "3:4"
}
"1941": {
    "game_name": "1941 - Counter Attack"
	"aspect_ration": "3:4"
},


"1943": {
    "game_name": "1943: The Battle of Midway"
	"aspect_ration": "3:4"
},


"19xx": {
    "game_name": "19XX - the war against destiny"
	"aspect_ration": "3:4"
},


"unsquad": {
    "game_name": "Area 88 / UN Squadron"
	"aspect_ration": "4:3"
},


"cawing": {
    "game_name": "Carrier Air Wing / US Navy"
	"aspect_ration": "4:3"
},


"ecofghtr": {
    "game_name": "Eco Fighters"
	"aspect_ration": "4:3"
},

"exedexes": {
    "game_name": "Exed Exes"
	"aspect_ration": "3:4"
},

"forgottn": {
    "game_name": "Forgotten Worlds"
	"aspect_ration": "4:3"
},

"gigawing": {
    "game_name": "Giga Wing"
	"aspect_ration": "4:3"
},

"lastduel": {
    "game_name": "Last Duel"
	"aspect_ration": "3:4"
},

"lwings": {
    "game_name": "Legendary Wings"
	"aspect_ration": "3:4"
},

"mmatrix": {
    "game_name": "Mars Matrix"
	"aspect_ration": "4:3"
},

"progear": {
    "game_name": "Progear"
	"aspect_ration": "4:3"
},

"sidearms": {
    "game_name": "Side Arms - Hyper Dyne"
	"aspect_ration": "4:3"
},

"varth": {
    "game_name": "Varth - Operation Thunderstorm"
	"aspect_ration": "3:4"
}
 "inthunt": {
    "game_name": "In The Hunt"
	"aspect_ration": "4:3"
},

"rtypeleo": {
    "game_name": "R-Type Leo"
	"aspect_ration": "4:3"
}
"salamand": {
    "game_name": "Salamander"
	"aspect_ration": "4:3"
  }
"raiden": {
    "game_name": "Raiden"
	"aspect_ration": "3:4"
},

"raiden2": {
    "game_name": "Raiden II"
	"aspect_ration": "3:4"	
},

"raidendx": {
    "game_name": "Raiden DX"
	"aspect_ration": "3:4"
}
"darius": {
    "game_name": "Darius"
	"aspect_ration": "12:3"
},

"darius2": {
    "game_name": "Darius II (Triple Screen)"
	"aspect_ration": "12:4"
},

"dariusg": {
    "game_name": "Darius Gaiden - Silver Hawk"
	"aspect_ration": "4:3"
},

"dariusgx": {
    "game_name": "Darius Gaiden - Silver Hawk Extra Version"
	"aspect_ration": "4:3"
},

"metalb": {
    "game_name": "Metal Black"
},

"spcinv95": {
    "game_name": "Space Invaders '95: The Attack Of Lunar Loonies"
	"aspect_ration": "3:4"
}
"batsugun": {
    "game_name": "Batsugun"
	"aspect_ration": "3:4"
},
	
"fireshrk": {
    "game_name": "Fire Shark"
	"aspect_ration": "3:4"
},

"truxton2": {
    "game_name": "Truxton II / Tatsujin-Oh"
	"aspect_ration": "3:4"
}`
MISSING:
metalb - Metal Black - Taito 1991

**Comment by glisignoli** [comment]
Done (Also did metal black)
