### ISSUE TITLE
FCReplay Game Support Request: Vampire Hunter (Darkstalkers 2)

### ISSUE THREAD

**Issue by BonesTOS** [glisignoli/fcreplay#114]
@glisignoli

Hello! I am requesting this game be supported by FCReplay.

Rom Name: vhuntjr2 
Game Name: Vampire Hunter - darkstalkers' revenge (950302 Japan)

**Comment by glisignoli** [comment]
Added

**Comment by BonesTOS** [comment]
Hello again! I think you may have added support to Vampire Hunter 2 instead (which is an expansion to Vampire Savior). The game I'm mentioning is https://www.fightcade.com/game/vhuntjr2 . Thanks again and sorry for all the trouble.

**Comment by glisignoli** [comment]
Error. Not sure how I made that mistake. I'll try and add it tomorrow

**Comment by glisignoli** [comment]
Ok actually done now
