### ISSUE TITLE
Game Request: Vampire - the night warriors (940630 Japan)

### ISSUE THREAD

**Issue by BonesTOS** [glisignoli/fcreplay#117]
@glisignoli 

Hello! I am requesting this game be supported by FCReplay.

Rom Name: VAMPJR1
Game Name: Vampire - the night warriors (940630 Japan)

Link to the exact game: https://www.fightcade.com/game/vampjr1

Thank you so much for all the work you put into this!

**Comment by glisignoli** [comment]
Done!
