### ISSUE TITLE
Game Request: Vampire Savior 2 - the lord of vampire (970913 Japan)

### ISSUE THREAD

**Issue by BonesTOS** [glisignoli/fcreplay#126]
@glisignoli

Hello! I am requesting this game be supported by FCReplay.

Rom Name: VSAV2
Game Name: Vampire Savior 2 - the lord of vampire (970913 Japan)

Link to the exact game: https://www.fightcade.com/game/vsav2

Thank you so much!

**Comment by glisignoli** [comment]
Done.

Don't know much about the series, but are these the same but just us/jp releases?

https://www.fightcade.com/game/vsavj
https://www.fightcade.com/game/vsav2
