### ISSUE TITLE
FCReplay Game Support Request: Vampire Savior Aesthetic Edition

### ISSUE THREAD

**Issue by BonesTOS** [glisignoli/fcreplay#128]
@glisignoli

Hello! I am requesting this game be supported by FCReplay.

Rom Name: vsavae
Game Name: #Vampire Savior - The Lord Of Vampire (Aesthetic Edition)

(It was added in the latest patch, it's a romhack for Vampire Savior that is going to be the one used competitively from now on).

**Comment by glisignoli** [comment]
Added, will be deployed shortly
