### ISSUE TITLE
FCReplay Game Support Request: Capcom's "Red Earth / War-Zard"

### ISSUE THREAD

**Issue by MasterO2** [glisignoli/fcreplay#66]
@glisignoli 

I am requesting this game also be supported by FCReplay.

It is a CPS-3 Game:

Rom Name: **redearth**
Game Name: Red Earth / War-Zard (Euro 961121)

Rom Name: **redearthr1**
Game Name: Red Earth / War-Zard (Euro 961023)

**Redearth** is the Parent Rom, **redearthr1** is the Clone.

**Comment by MasterO2** [comment]
@glisignoli Any progress on this issue? I do not see it yet listed http://fightcadevids.com/ yet.

**Comment by glisignoli** [comment]
Its been added but just not deployed out yet. I want to make the configuration independent of the recording machine so I don't need to redeploy the machine for a simple configuration change.

I'm actually interested to see some matches so I'll try and deploy it in a few hours and post here once it's done.

**Comment by glisignoli** [comment]
@MasterO2 I've added the game. Try submitting it now

**Comment by Doublethefun27** [comment]
My friend and I attempted to submit replays and were met multiple times with an "Internal Server Error," and have so far been unable to submit them

**Comment by glisignoli** [comment]
Sorry! I see the problem, I'll fix it today/tomorrow.

**Comment by glisignoli** [comment]
@MasterO2 Ok it should be fixed now. Sorry!

**Comment by Bailey-Rudolph** [comment]
It does appear to be fixed, thanks very much!

**Comment by MasterO2** [comment]
To all involved: 

I will close that issue thread once the Red Earth videos show up on fightcadevids.com itself.  I just want to make sure they show up correctly first.

**Comment by glisignoli** [comment]
This it? https://archive.org/details/1600635536243-2756
It's encoded, just waiting for archive.org to process it.

**Comment by MasterO2** [comment]
> 
> 
> This it? https://archive.org/details/1600635536243-2756
> It's encoded, just waiting for archive.org to process it.

That's one of them.  There should also be a couple more Red Earth videos in the queue as well, but I'm not the uploader of any those.  I merely asked people on the Red Earth Discord channel to make sure it's working correctly.

**Comment by MasterO2** [comment]
@glisignoli 

The Red Earth videos are there now, so I am closing this issue.
