### ISSUE TITLE
FCReplay Game Support Request: Capcom's "X-Men Children Of The Atom" 

### ISSUE THREAD

**Issue by DeadweightMugs** [glisignoli/fcreplay#72]
@glisignoli 

I am requesting this game also be supported by FCReplay.

It is a CPS-2 Game:

Rom Name: xmcota
Game Name: X-Men Children Of The Atom (950331 Euro)

**Comment by glisignoli** [comment]
I've got a bunch of backend work to do first. But I'll update this once I've added it.

**Comment by glisignoli** [comment]
Added to configuration but not deployed yet

**Comment by glisignoli** [comment]
Deployed!
