### ISSUE TITLE
FCReplay Game Support Request: Capcom's "Cyberbots - Fullmetal Madness"

### ISSUE THREAD

**Issue by MasterO2** [glisignoli/fcreplay#74]
@glisignoli 

I am requesting this game be supported by FCReplay.

Rom Name:  **cybots**
Game Name: Cyberbots - Fullmetal Madness (950424 Euro)

**Comment by glisignoli** [comment]
Added to configuration but not deployed yet

**Comment by glisignoli** [comment]
Deployed!
