### ISSUE TITLE
FCReplay Game Support Request: SNK's "Savage Reign" and "Kizuna Encounter - Super Tag Battle"

### ISSUE THREAD

**Issue by MasterO2** [glisignoli/fcreplay#75]
@glisignoli 

Both games are for the Neo-Geo arcade system.  Kizuna Encounter is the direct sequel to Savage Reign.

Rom Name: **savagere**
Game Name: Savage Reign

Rom Name: **kizuna**
Game Name: Kizuna Encounter - Super Tag Battle

[Kizuna Encounter's Discord Channel](https://discord.gg/abkMyc)  (Savage Reign is also covered in that Discord channel)

**Comment by glisignoli** [comment]
Added to configuration but not deployed yet

**Comment by glisignoli** [comment]
Deployed!
