### ISSUE TITLE
FCReplay Game Support Request: The Remaining Marvel Arcade Fighting Games

### ISSUE THREAD

**Issue by MasterO2** [glisignoli/fcreplay#77]
@glisignoli  

Since X-men: Children of the Atom is now supported, here are the others:

1)

Rom Name: **msh**
Game Name: Marvel Super Heroes (951024 Euro) 

2)

Rom Name: **xmvsf**
Game Name: X-Men vs Street Fighter (961004 Euro)

3)

Rom Name: **mshvsf**
Game Name: Marvel Super Heroes vs Street Fighter (970625 Euro)

4)

Rom Name: **mvsc**
Game Name: Marvel vs Capcom - clash of super heroes (980123 Euro)

**Comment by glisignoli** [comment]
I've got to fix a bug with the audio sync, once that's done I'll add them.

**Comment by glisignoli** [comment]
Done
