### ISSUE TITLE
FCReplay Game Support Request: Remaining Neo Geo Fighters Actively Played on Fightcade

### ISSUE THREAD

**Issue by MasterO2** [glisignoli/fcreplay#78]
@glisignoli 

This should cover most of the remaining Neo Geo fighters actively played on Fightcade that are **not** already on fightcadevids.com:

Rom Name: **3countb**
Game Name: 3 Count Bout / Fire Suplex

Rom Name: **aodk**
Game Name: Aggressors of Dark Kombat

Rom Name: **aof**
Game Name: Art of Fighting

Rom Name: **aof2**
Game Name: Art of Fighting 2

Rom Name: **doubledr**
Game Name: Double Dragon (Neo-Geo)

Rom Name: **lastblad**
Game Name: The Last Blade

Rom Name: **wh1**
Game Name: World Heroes

Rom Name: **wh2**
Game Name: World Heroes 2

Rom Name: **wh2j**
Game Name: World Heroes 2 Jet

Rom Name: **whp**
Game Name: World Heroes Perfect

The rom names should be correct, but just do a final double check to make sure they're ok.

**Comment by glisignoli** [comment]
Names were perfect! Thanks!
