### ISSUE TITLE
FCReplay Game Support Request: Breakers 1, Galaxy Fight, Kabuki Clash, Ninja Masters, Voltage Fighter Gowcaizer

### ISSUE THREAD

**Issue by MasterO2** [glisignoli/fcreplay#79]
@glisignoli 

Rom Name: **breakers**
Game Name: Breakers

Rom Name: **galaxyfg**
Game Name: Galaxy Fight - Universal Warriors

Rom Name: **kabukikl**
Game Name: Kabuki Klash - Far East of Eden

Rom Name: **ninjamas**
Game Name: Ninja Master's / Haoh Ninpo Cho

Rom Name: **gowcaizr**
Game Name: Voltage Fighter - Gowcaizer

And with those final romsets, fightcadevids.com should now cover **all fighting games released for the Neo Geo**, unless you can think of any that are missing.

In terms of fighting games, that's it from me for the moment. If I think of any other fighters that aren't on fightcadevids.com, I'll make future requests.

**Comment by glisignoli** [comment]
Done!
