### ISSUE TITLE
FCReplay Game Support Request: Neo Geo Sports Games

### ISSUE THREAD

**Issue by MasterO2** [glisignoli/fcreplay#80]
@glisignoli 

Neo Geo Sports Games:

Note: All rom names should be correct, but just double check that there aren't any typos:

Rom Name: **2020bb**
Game Name: 2020 Super Baseball

Rom Name: **bangbead**
Game Name: Bang Bead

Rom Name: **bstars2**
Game Name: Baseball Stars 2

Rom Name: **flipshot**
Game Name: Battle Flip Shot

Rom Name: **fbfrenzy**
Game Name: Football Frenzy

Note: (You may want to add "American" before the word Football in the game title, to avoid confusion with Soccer / Association Football).

Rom Name: **goalx3**
Game Name: Goal! Goal! Goal!

Rom Name: **lbowling**
Game Name: League Bowling 

Rom Name: **neocup98**
Game Name: Neo-Geo Cup '98 - The Road to the Victory

Rom Name: **pgoal**
Game Name: Pleasure Goal

Rom Name: **socbrawl**
Game Name: Soccer Brawl

Rom Name: **ssideki**
Game Name: Super Sidekicks

Rom Name: **ssideki2**
Game Name: Super Sidekicks 2 - The World Championship

Rom Name: **ssideki3**
Game Name: Super Sidekicks 3 - The Next Glory

Rom Name: **ssideki4**
Game Name: The Ultimate 11 - The SNK Football Championship

Note: (You may want to add "Association" after SNK, to avoid confusion with American Football).

Rom Name: **strhoop**
Game Name: Street Hoop

Rom Name: **turfmast**
Game Name: Neo Turf Masters

**Comment by glisignoli** [comment]
Done

Going to keep the game names the same though
