### ISSUE TITLE
FCReplay Game Support Request: Mortal Kombat 1 - 3, Puzzle Fighter, and Gem Fighter

### ISSUE THREAD

**Issue by MasterO2** [glisignoli/fcreplay#83]
@glisignoli 

> CPS-2 Street Fighter 2 Parody Games

Rom Name: **spf2t**
Game Name: Super Puzzle Fighter II Turbo

Rom Name: **sgemf**
Game Name: Super Gem Fighter Mini Mix

> Mortal Kombat 1, 2, and 3

Rom Name: **mk**
Game Name: Mortal Kombat

Rom Name: **mk2**
Game Name: Mortal Kombat II

Note: the second game uses a roman numeral for the number 2, but the other Mortal Kombat games do not.

Rom Name: **mk3**
Game Name: Mortal Kombat 3

**Comment by glisignoli** [comment]
Done

Note: MK1 Doesn't seem to be supported by Fightcade

**Comment by MasterO2** [comment]
> 
> 
> Done
> 
> Note: MK1 Doesn't seem to be supported by Fightcade

@glisignoli MK1 is now supported by Fightcade, so that is no longer an issue.

**Comment by glisignoli** [comment]
MK1 Done

**Comment by Conspiratorial** [comment]
Rom name: Jchan
Game name: Jackie Chan - The Kung-Fu Master

**Comment by Conspiratorial** [comment]
Rom name: sf
Game name: Street Fighter (US, set 1)
