### ISSUE TITLE
http://www.fightcadevids.com/about - Games Listed There Are Not in Alphabetical Order

### ISSUE THREAD

**Issue by MasterO2** [glisignoli/fcreplay#88]
@glisignoli

The games listed on http://www.fightcadevids.com/about are **not** in alphabetical order.  They appear to be in rom name order.

Same idea as the recently fixed issue https://github.com/glisignoli/fcreplay/issues/84

**Comment by glisignoli** [comment]
Should be an easy fix. Will look at it tonight

**Comment by glisignoli** [comment]
Tonight.... Done....
