### ISSUE TITLE
Add Video Submission Instructions to http://www.fightcadevids.com/submit

### ISSUE THREAD

**Issue by MasterO2** [glisignoli/fcreplay#89]
@glisignoli 

For the http://www.fightcadevids.com/submit page:

> You can upload your Fightcade match videos to https://www.fightcadevids.com/ using the challenge URLs from https://www.fightcade.com/replay/. Fightcade videos are found on the replay site by searching by your game's rom name, for example sf2ce for Street Fighter 2: Championship Edition.  On the replay site, right click on the blue "View Replay" button for the match you want to upload, copy the link location, and then paste that copied link into http://www.fightcadevids.com/submit.  Just note though that videos will not appear immediately.  The time to encode and upload your video to Fightcadevids will depend on how long the video is and the site's queue size.  

You can edit the above text however you want.

**Comment by glisignoli** [comment]
Nice work. I'll also try and improve the status messages while I'm at it

**Comment by glisignoli** [comment]
Updated the submit page, haven't fixed the status messages
